//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuvar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fuvar.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to taxi_id;indulas;idotartam;tavolsag;viteldij;borravalo;fizetes_modja
        ///5240;2016-12-15 23:45:00;900;2,5;10,75;2,45;bankkártya
        ///1215;2016-12-12 07:15:00;240;0,4;5,0;3,0;bankkártya
        ///3673;2016-12-16 16:30:00;2400;10,7;31,0;0,0;készpénz
        ///5400;2016-12-16 08:45:00;300;0,0;5,25;2,0;bankkártya
        ///1257;2016-12-03 18:45:00;360;0,3;5,0;0,0;készpénz
        ///4666;2016-12-30 18:00:00;2400;18,2;46,75;10,15;bankkártya
        ///5998;2016-12-16 07:15:00;1800;18,4;45,0;11,25;bankkártya
        ///2538;2016-12-31 17:15:00;540;0,0;6,75;0,0;készpénz
        ///6594;2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fuvar {
            get {
                return ResourceManager.GetString("fuvar", resourceCulture);
            }
        }
    }
}
